### ISSUE TITLE
Incomplete package.xml and CMakeLists.txt

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/hero_bringup#18]
The package.xml and CMakeLists.txt does not have all the dependencies defined.

If this package is installed and built independent of our tool chain, then executing the launch files gives errors and warnings as the dependent packages are not in the catkin_ws. 

The workspace should not build in the first place when these dependent packages are not present.

**Comment by MatthijsBurgh** [comment]
Both package.xml and CMakeLists.txt only define software dependencies no ros dependencies.

**Comment by ar13pit** [comment]
> Both package.xml and CMakeLists.txt only define software dependencies, no ros dependencies.

I don't quite understand what you mean by software and ros dependencies

**Comment by LoyVanBeek** [comment]
I think he means ROS dependencies (ros packages) and system dependencies (eg. like qt, glibc etc). 
Right @MatthijsBurgh? Otherwise, I don't know what you mean.

**Comment by MatthijsBurgh** [comment]
I mean ROS launch dependencies. For example. `robot_skills` interacts by ROS with `ED`. So for it to work, you need to have to run `ED` as well. However `ED` shouldn't be a dependency of `robot_skills`, as it runs without `ED`. Behaviour of it will be shit, as all service calls will fail. But no software dependency of `robot_skills` to `ED` exist.

**Comment by MatthijsBurgh** [comment]
@ar13pit Do you understand?

**Comment by ar13pit** [comment]
Yes I do. But we still need a better way of defining these dependencies because missing dependencies must show during workspace build and not execution.
